### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [SmartCalendar/SmartCalendar#20]
Looks like you did not implement the following user story:

- No completed user stories in README was checked-off.

We encourage everyone to complete all the [required user stories](https://courses.codepath.org/snippets/android_university/grading) for each assignment to demonstrate topic understanding. While we **won't** be regrading this submission anymore, we hope you try to complete all required user stories [indicated here](https://courses.codepath.org/snippets/android_university/grading) or on the Course Portal assignment tab for **future assignments**.

**Comment by ericloufoua** [comment]
All done
