### ISSUE TITLE
Can someone help me build out the Notifications menu/layout

### ISSUE THREAD

**Issue by aramdov** [SmartCalendar/SmartCalendar#26]
I need a menu like in the image below. Where you can click anywhere in each "row".
Ideally, I'd like this to open up inside EditActivity after click the "Add Notification" EditText. I'll link the buttons to actions to create an alarm but I need help on creating this screen as I don't remember much about recyclerview. I don't understand recyclerview that well either.

![image](https://user-images.githubusercontent.com/45133554/101566849-91d42d80-3984-11eb-838a-a6f2ad3120b3.png)

**Comment by ericloufoua** [comment]
Done
