### ISSUE TITLE
Building Views for Calendar (Daily, weekly, etc) and UX/Design

### ISSUE THREAD

**Issue by jtmlock** [SmartCalendar/SmartCalendar#8]

**Comment by saheelsapovadia** [comment]
I am newbie to open source development and want to start contributing. I have some knowledge of Android Development. It would really help if you could provide some description for this issue.

**Comment by saheelsapovadia** [comment]
> 
> 
> I am newbie to open source development and want to start contributing. I have some knowledge of Android Development. It would really help if you could provide some description for this issue.

waiting for your reply...
